#!/bin/bash

export GOPATH=$PWD/
# export GOMAXPROCS=1

# Abort on errors after this point ...
set -e

# Make sure the app builds
./build || exit $?


echo ""
echo ".................................................................."
echo "Running tests ...................................................."
echo ".................................................................."
echo ""

go test $@ ./encryption_utils/... || exit $?

echo ""
echo ".................................................................."
echo "Finished tests ..................................................."
echo ".................................................................."
echo ""
